title: FR Test Data
author: federgraph
description: >- # this means to ignore newlines until "baseurl:"
  sailing regatta event data files and posts
baseurl: ""  # the subpath of your site, e.g. /blog
url: https://github.com/federgraph/fleetrace-examle-data/
github_username: federgraph
repository: federgraph/fleetrace-example-data
permalink: /:title:output_ext
github: [metadata]

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - tsconfig.json
#  - node_modules
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
  - src